ARG TERRAFORM_VERSION
FROM hashicorp/terraform:${TERRAFORM_VERSION} AS build-env

FROM scratch
MAINTAINER Shigure Onishi <s.onishi@kakehashi.life>
COPY --from=build-env /bin/terraform /bin/terraform
ADD ./tmp /tmp
ENTRYPOINT ["/bin/terraform"]
CMD ["--help"]
